apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-ns
  name: my-ns
spec:
  ports:
  - port: 80
    protocol: TCP
    nodePort: 30080
    targetPort: 80
  selector:
    app: wordpress
  type: NodePort

