apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wordpress
  name: wordpress-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: wordpress
        name: wordpress
        env:
          - name: WORDPRESS_DB_HOST
            value: "clusterip-node"
          - name: WORDPRESS_DB_USER
            valueFrom:
              secretKeyRef:
                name: wp-secret
                key: wp_db_user
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: wp-secret
                key: wp_db_psswd
          - name: WORDPRESS_DB_NAME
            value: "wordpressdb"
        volumeMounts:
          - name: wordpress-volume
            mountPath: /var/www/html
        ports:
        - containerPort: 80
      volumes:
        - name: wordpress-volume
          hostPath:
            path: /data
            type: DirectoryOrCreate
